version: "3.9"
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    expose:
      - 8000
    ports:
      - "8000-8000"
    volumes:
      - ./server:/server
      - dev-static-data:/vol/web
    command: >
      sh -c "
            python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - ./.env


volumes:
  dev-db-data:
  dev-static-data:

