# Generated by Django 4.1.5 on 2023-02-03 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('loans', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
