# Generated by Django 4.1.5 on 2023-02-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='overtime',
            new_name='overtime_work',
        ),
    ]
