# Generated by Django 3.2.17 on 2023-02-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20230209_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='user',
            new_name='employee',
        ),
    ]
