# Generated by Django 3.2.17 on 2023-02-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_user_salary_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='not@provided.com', max_length=254),
        ),
    ]
