# Generated by Django 3.2.17 on 2023-02-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_person_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id']},
        ),
    ]
