# Generated by Django 4.1.5 on 2023-02-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('products', '0004_alter_fiberbag_receipt_alter_pillow_receipt'),
        ('receipts', '0002_customerreceipt_suppliersreceipt_and_more'),
        ('customers', '0002_remove_customerprofile_state_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.AddField(
            model_name='suppliersreceipt',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_receipt', to='suppliers.supplierprofile'),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_receipt', to='customers.customerprofile'),
        ),
    ]
