# Generated by Django 4.1.5 on 2023-02-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_transaction_date_and_more'),
        ('products', '0006_remove_fiberbag_receipt_remove_pillow_receipt'),
        ('receipts', '0003_delete_receipt_suppliersreceipt_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreceipt',
            name='fiber_bag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_receipt', to='products.fiberbag'),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='pillow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_receipt', to='products.pillow'),
        ),
        migrations.AddField(
            model_name='suppliersreceipt',
            name='material',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_receipt', to='materials.material'),
            preserve_default=False,
        ),
    ]
