# Generated by Django 4.1.5 on 2023-02-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='government',
            field=models.CharField(default='giza', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
