# Generated by Django 4.1.5 on 2023-02-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('bank', 'Bank'), ('e_wallet', 'E-Wallet'), ('postal', 'Postal')], max_length=50),
        ),
    ]
