version: "3"
services:
  backend:
      container_name: "backend"
      build: .
      command: >
        bash -c "
        python manage.py makemigrations && 
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
        "
      expose:
        - 8000
      ports:
        - "8001:8000"
      volumes:
        - ./:/server
      env_file:
        - ./.env
      environment:
        - DJANGO_SETTINGS_MODULE=textile_shop.settings
      depends_on:
        - db
  
  db:
    image: postgres
    container_name: "db"
    ports:
      - "5432:5432"
    volumes:
        - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yusuf
      - POSTGRES_DB=yusuf
