# Generated by Django 4.1.5 on 2023-02-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pillow',
            name='size',
            field=models.CharField(default='50x50', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fiberbag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='category',
            field=models.CharField(choices=[('fiberic', 'قماش'), ('pillow_slip', 'كبس'), ('fiber', 'فايبر')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='type',
            field=models.CharField(choices=[('pillow', 'مخدة'), ('circular_pillow', 'خددية')], max_length=20),
        ),
    ]
