# Generated by Django 3.2.17 on 2023-02-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiberbag',
            name='bag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.bag'),
        ),
        migrations.AlterField(
            model_name='fiberbag',
            name='fiber',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.fiber'),
        ),
        migrations.AlterField(
            model_name='fiberbag',
            name='fibric',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.fabric'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='bag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.bag'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='fiber',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.fiber'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='fibric',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.fabric'),
        ),
    ]
