# Generated by Django 4.1.5 on 2023-02-02 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
        ('products', '0002_pillow_size_alter_fiberbag_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiberbag',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiber_bag', to='receipts.receipt'),
        ),
        migrations.AddField(
            model_name='pillow',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pillow', to='receipts.receipt'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='category',
            field=models.CharField(choices=[('قماش', 'قماش'), ('كبس', 'كبس'), ('فايبر', 'فايبر')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='type',
            field=models.CharField(choices=[('مخدة', 'مخدة'), ('خددية', 'خددية')], max_length=20),
        ),
    ]
