# Generated by Django 3.2.17 on 2023-02-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230207_1358'),
        ('products', '0002_auto_20230211_1230'),
    ]

    operations = [
    ]
