# Generated by Django 4.1.5 on 2023-02-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_customerreceipt_suppliersreceipt_and_more'),
        ('products', '0003_fiberbag_receipt_pillow_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiberbag',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiber_bag', to='receipts.customerreceipt'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pillow', to='receipts.customerreceipt'),
        ),
    ]
