# Generated by Django 4.1.5 on 2023-02-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_delete_receipt_suppliersreceipt_supplier_and_more'),
        ('products', '0004_alter_fiberbag_receipt_alter_pillow_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiberbag',
            name='receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiber_bag', to='receipts.customerreceipt'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pillow', to='receipts.customerreceipt'),
        ),
    ]
