# Generated by Django 4.1.5 on 2023-02-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_fiberbag_receipt_alter_pillow_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiberbag',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='pillow',
            name='receipt',
        ),
    ]
