# Generated by Django 4.1.5 on 2023-02-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='transaction_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='material',
            name='types_of_transactions',
            field=models.CharField(choices=[('buy', 'buy'), ('return', 'return')], default='buy', max_length=10),
            preserve_default=False,
        ),
    ]
